#!/usr/bin/env bash

# dmenu theming
lines="-l 8 -z 1916"
font="-fn Inconsolata-13"
colors="-nb #1e1e2e -nf #cdd6f4 -sb #f38ba8 -sf #1e1e2e -nhb     #f38ba8 -nhf #1e1e2e -shb #1e1e2e -shf #f38ba8"

selected="$(ps -a -u $USER | \
            dmenu -i -p "Type to search and select process to kill" \
            $lines $colors $font | \
            awk '{print $1" "$4}')"; 

if [[ ! -z $selected ]]; then

    answer="$(echo -e "Yes\nNo" | \
            dmenu -i -p "$selected will be killed, are you sure?" \
            $lines $colors $font )"

    if [[ $answer == "Yes" ]]; then
        selpid="$(awk '{print $1}' <<< $selected)"; 
        kill -9 $selpid
    fi
fi

exit 0
